/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_RampStackShader_TemporalInterpType */

#ifndef _Included_com_mousebird_maply_imagerypro_RampStackShader_TemporalInterpType
#define _Included_com_mousebird_maply_imagerypro_RampStackShader_TemporalInterpType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
