/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_QuadImageTileLayer_ImagePositionFeedback */

#ifndef _Included_com_mousebird_maply_imagerypro_QuadImageTileLayer_ImagePositionFeedback
#define _Included_com_mousebird_maply_imagerypro_QuadImageTileLayer_ImagePositionFeedback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
