/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_IProQuadImageTileLayer */

#ifndef _Included_com_mousebird_maply_imagerypro_IProQuadImageTileLayer
#define _Included_com_mousebird_maply_imagerypro_IProQuadImageTileLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setEnable
 * Signature: (ZLcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setEnable
  (JNIEnv *, jobject, jboolean, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setDrawPriority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setDrawPriority
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setImageDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setImageDepth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    getImageDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_getImageDepth
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    getCurrentImage
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_getCurrentImage
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setCurrentImageSimple
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setCurrentImageSimple
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setCurrentImages
 * Signature: (IILcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setCurrentImages
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setMaxCurrentImage
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setMaxCurrentImage
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setAllowFrameLoading
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setAllowFrameLoading
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    getFrameStatusNative
 * Signature: ([Z[I)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_getFrameStatusNative
  (JNIEnv *, jobject, jbooleanArray, jintArray);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setFrameLoadingPriority
 * Signature: ([ILcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setFrameLoadingPriority
  (JNIEnv *, jobject, jintArray, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setColor
 * Signature: (FFFFLcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setMaxTiles
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setMaxTiles
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setImportanceScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setImportanceScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setTextureAtlasSizeNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setTextureAtlasSizeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    getBorderTexel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_getBorderTexel
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setBorderTexel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setBorderTexel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setMultiLevelLoads
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setMultiLevelLoads
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    getTargetZoomLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_getTargetZoomLevel
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    reload
 * Signature: (Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_reload
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setSimultaneousFetches
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setSimultaneousFetches
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setUseTargetZoomLevel
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setUseTargetZoomLevel
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setSingleLevelLoading
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setSingleLevelLoading
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setHandleEdges
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setHandleEdges
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setCoverPoles
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setCoverPoles
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setVisibility
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setVisibility
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setInternalImageFormatNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setInternalImageFormatNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    setShaderNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_setShaderNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeShutdown
 * Signature: (Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeShutdown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystem;Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_initialise
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeStartLayer
 * Signature: (Lcom/mousebird/maply/Scene;Lcom/mousebird/maply/MaplyRenderer;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeStartLayer
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeViewUpdate
 * Signature: (Lcom/mousebird/maply/ViewState;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeViewUpdate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeEvalStep
 * Signature: (Lcom/mousebird/maply/ChangeSet;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeEvalStep
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeRefresh
 * Signature: (Lcom/mousebird/maply/ChangeSet;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeRefresh
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeTileDidLoad
 * Signature: (IIIILandroid/graphics/Bitmap;Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeTileDidLoad__IIIILandroid_graphics_Bitmap_2Lcom_mousebird_maply_ChangeSet_2
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeTileDidLoad
 * Signature: (IIII[Landroid/graphics/Bitmap;Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeTileDidLoad__IIII_3Landroid_graphics_Bitmap_2Lcom_mousebird_maply_ChangeSet_2
  (JNIEnv *, jobject, jint, jint, jint, jint, jobjectArray, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_IProQuadImageTileLayer
 * Method:    nativeTileDidNotLoad
 * Signature: (IIIILcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_nativeTileDidNotLoad
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
