/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_AttrDictionary */

#ifndef _Included_com_mousebird_maply_AttrDictionary
#define _Included_com_mousebird_maply_AttrDictionary
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mousebird_maply_AttrDictionary_TYPE_INT
#define com_mousebird_maply_AttrDictionary_TYPE_INT 1L
#undef com_mousebird_maply_AttrDictionary_TYPE_DOUBLE
#define com_mousebird_maply_AttrDictionary_TYPE_DOUBLE 2L
#undef com_mousebird_maply_AttrDictionary_TYPE_STRING
#define com_mousebird_maply_AttrDictionary_TYPE_STRING 3L
/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_AttrDictionary_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getInt
 * Signature: (Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_AttrDictionary_getInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getDouble
 * Signature: (Ljava/lang/String;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_AttrDictionary_getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    setInt
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_setInt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    setDouble
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_setDouble
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getKeys
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mousebird_maply_AttrDictionary_getKeys
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_AttrDictionary_getType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
