/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_IProQuadImageTileLayer_FrameStatus */

#ifndef _Included_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_FrameStatus
#define _Included_com_mousebird_maply_imagerypro_IProQuadImageTileLayer_FrameStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
