/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_RampStackShader_SpatialInterpType */

#ifndef _Included_com_mousebird_maply_imagerypro_RampStackShader_SpatialInterpType
#define _Included_com_mousebird_maply_imagerypro_RampStackShader_SpatialInterpType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
