/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_ShaderGenerator_ShaderVersion */

#ifndef _Included_com_mousebird_maply_imagerypro_ShaderGenerator_ShaderVersion
#define _Included_com_mousebird_maply_imagerypro_ShaderGenerator_ShaderVersion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
