/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_ShaderGenerator */

#ifndef _Included_com_mousebird_maply_imagerypro_ShaderGenerator
#define _Included_com_mousebird_maply_imagerypro_ShaderGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    setVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_setVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    setGlobalPrecision
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_setGlobalPrecision
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    addGlobalCodeBlock
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_addGlobalCodeBlock
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    addGlobalVariable
 * Signature: (IIILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_addGlobalVariable
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    addFunction
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_addFunction
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    replaceStringInFunctions
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_replaceStringInFunctions
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    generateShaders
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_generateShaders
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    getVertexShader
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_getVertexShader
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    getFragmentShader
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_getFragmentShader
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_ShaderGenerator
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_ShaderGenerator_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
