/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_imagerypro_RampStackShader */

#ifndef _Included_com_mousebird_maply_imagerypro_RampStackShader
#define _Included_com_mousebird_maply_imagerypro_RampStackShader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setTexelInputType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setTexelInputType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setIndexType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setIndexType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setPixelByteOrder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setPixelByteOrder
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setStackType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setStackType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setStackCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setStackCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setTemporalInterpolation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setTemporalInterpolation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    setSpatialInterpolation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_setSpatialInterpolation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_imagerypro_RampStackShader
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_imagerypro_RampStackShader_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
